### ISSUE TITLE
`--` missing in NPM script call on https://formatjs.io/docs/tooling/cli/#compilation

### ISSUE THREAD

**Issue by jfhector** [formatjs/formatjs.github.io#2]
First, thanks for the great library.

## The issue

On the page https://formatjs.io/docs/tooling/cli/#compilation, I read:
```
npm run compile --help
```

Running that command doesn't work. I get:
```
$ npm run compile --help
No results for "run" "compile"
```

That's because `--` is needed when passing options as part of executing a NPM script:
This works:
```
$ npm run compile -- --help
```

The same issue happens here too:
```
npm run extract --help
```

**Comment by longlho** [comment]
all the code is actually at formatjs/formatjs repo so you'd have to submit a PR there
