### ISSUE TITLE
Search is broken

### ISSUE THREAD

**Issue by shadow-identity** [formatjs/formatjs.github.io#3]
Site search does not work ATM: neither by pressing cmd+k nor by mouse click, neither in latest stable Chrome, nor in Firefox Beta.
Repro: 
1. https://formatjs.io/docs/intl/#message-formatting-fallbacks
2. cmd+k or click on Search button
3. nothing happens (default search thingy opens in Firefox by Cmd+K, but not the site one)
4. open browser console
5. observe multiple errors starting from 
```
GET
https://formatjs.io/docs/intl/&#x27;https://fonts.googleapis.com/css2?family=Instrument+Sans:ital,wght@0,400..700;1,400..700&amp;display=swap&#x27;
[HTTP/2 404  23ms]

Docusaurus React Root onRecoverableError: Error: Minified React error #425; visit https://reactjs.org/docs/error-decoder.html?invariant=425 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

**Comment by longlho** [comment]
this's been fixed
